// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN3kKl-7iF3jrbiiHNGvaTJk3Ue0LfmfE',
    appId: '1:282685155183:web:0170e9d40f8a6bcea7ea9a',
    messagingSenderId: '282685155183',
    projectId: 'mapbox-flutter-fed9f',
    authDomain: 'mapbox-flutter-fed9f.firebaseapp.com',
    storageBucket: 'mapbox-flutter-fed9f.appspot.com',
    measurementId: 'G-S5Y2F14B1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcvl-GM2wMruaR7CeGfa4p5JMWW-YueqU',
    appId: '1:282685155183:android:c175ccbbc17a41aea7ea9a',
    messagingSenderId: '282685155183',
    projectId: 'mapbox-flutter-fed9f',
    storageBucket: 'mapbox-flutter-fed9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEd1v6kP0fSJhTbm7LXFt7x6tAcpC_14U',
    appId: '1:282685155183:ios:b8c093a29829fefba7ea9a',
    messagingSenderId: '282685155183',
    projectId: 'mapbox-flutter-fed9f',
    storageBucket: 'mapbox-flutter-fed9f.appspot.com',
    iosClientId: '282685155183-o34mrjh4v0e972kc4b6rg9241e0umf06.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMapboxBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEd1v6kP0fSJhTbm7LXFt7x6tAcpC_14U',
    appId: '1:282685155183:ios:b8c093a29829fefba7ea9a',
    messagingSenderId: '282685155183',
    projectId: 'mapbox-flutter-fed9f',
    storageBucket: 'mapbox-flutter-fed9f.appspot.com',
    iosClientId: '282685155183-o34mrjh4v0e972kc4b6rg9241e0umf06.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMapboxBlog',
  );
}
